# Generated by Django 4.1 on 2022-08-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('T', 'Tool'), ('S', 'Shelter'), ('O', 'Outfit')], default='T', max_length=1)),
                ('description', models.TextField(max_length=200)),
                ('durability', models.CharField(choices=[('W', 'Worn'), ('U', 'Used'), ('N', 'Unused')], default='W', max_length=1)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=1)),
            ],
        ),
    ]
